project_id = "vpugfhmddyttrokzbsqr"

[functions.transcribe-voice]
verify_jwt = true

[functions.generate-career-paths]
verify_jwt = true

[functions.generate-voice-focused-paths]
verify_jwt = true

[functions.generate-path-images]
verify_jwt = true

[functions.generate-featured-content]
verify_jwt = true

[functions.generate-goals]
verify_jwt = true

[functions.generate-insights]
verify_jwt = true

[functions.generate-personalized-guidance]
verify_jwt = true

[functions.parse-cv]
verify_jwt = true

[functions.generate-level-resources]
verify_jwt = true

[functions.generate-daily-motivation]
verify_jwt = true

[functions.generate-personalized-mentors]
verify_jwt = true

[functions.generate-skill-gap]
verify_jwt = true

[functions.generate-daily-missions]
verify_jwt = true

[functions.generate-shortcuts]
verify_jwt = true

[functions.generate-affirmations]
verify_jwt = true

[functions.happenstance-search]
verify_jwt = true

[functions.generate-mentor-embeddings]
verify_jwt = false

