project_id = "vpugfhmddyttrokzbsqr"

[functions.transcribe-voice]
verify_jwt = false

[functions.generate-career-paths]
verify_jwt = true

[functions.generate-path-images]
verify_jwt = true

[functions.generate-featured-content]
verify_jwt = true

[functions.generate-goals]
verify_jwt = true

[functions.generate-insights]
verify_jwt = true